service: rallyboard

frameworkVersion: ">=1.1.0 <2.0.0"

plugins:
  - serverless-dynamodb-local
  - serverless-offline
custom:
  offline:
    local: true
    other: false
  endpoints:
    dynamodb-url: 'http://localhost:8000'
  dynamodb:
    start:
      migrate: true
    stages:
      - local

provider:
  name: aws
  stage: ${opt:stage, 'local'}
  region: ${opt:region, 'eu-north-1'}
  runtime: nodejs10.x
  environment:
    DYNAMODB_TABLE: ${self:service}-stagetimes-${self:provider.stage}
    CONFIG_DYNAMODB_ENDPOINT: ${self:custom.endpoints.dynamodb-url}
    IS_OFFLINE: ${self:custom.offline.${self:provider.stage}, self:custom.offline.other}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

functions:
  create:
    handler: stagetimes/create.create
    events:
      - http:
          path: stagetimes
          method: post
          cors: true

  list:
    handler: stagetimes/list.list
    events:
      - http:
          path: stagetimes
          method: get
          cors: true

  get:
    handler: stagetimes/get.get
    events:
      - http:
          path: stagetimes/{id}
          method: get
          cors: true

resources:
  Resources:
    StageTimesDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: game-country-stage
            AttributeType: S
          - AttributeName: time
            AttributeType: N
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
        GlobalSecondaryIndexes:
        - IndexName: stageGSI
          KeySchema:
          - AttributeName: game-country-stage
            KeyType: HASH
          - AttributeName: time
            KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
